### ISSUE TITLE
ES6 vs WASM website won't work

### ISSUE THREAD

**Issue by qpwo** [leefsmp/Particle-System#2]
When I fire [this](https://leefsmp.github.io/Particle-System/Test/Test%20-%20vs/ES6-vs-WASM.html) up and click Run Test, it fails and the console shows:
```
--------- Running ES6 Test --------- 
worker.bundle.js:3:23974
--------- Running WASM Test --------- 
worker.bundle.js:3:24118
Unhandled promise rejection TypeError: n.ParticleSystem is not a constructor
```

**Comment by leefsmp** [comment]
yeah, I compiled this wasm a while ago, it's not compatible anymore with current browsers. You would need to install the latest [emscripten](https://github.com/kripken/emscripten) and build it yourself...
